Add new inscription
cypherpunklab/manifesto pull request #119
Opened 2023-07-07 21:25 UTC by sfhoo

Well, the latest merge request from others broke mine... Create another with my inscription id.

2023-07-08 00:20 UTC, elocremarc approved these changes

2023-07-08 00:23 UTC, elocremarc requested changes
Need to fix conflicts with main before merging

2023-07-08 19:23 UTC, sfhoo commented
Done

2023-07-14 08:31 UTC, elocremarc approved these changes

2023-07-14 08:34 UTC, merged