Add new inscription ID
cypherpunklab/manifesto pull request #243
Opened 2023-07-26 05:47 UTC by 759894780

2023-07-26 06:27 UTC, elocremarc requested changes
Only submit 1 inscription

2023-07-26 06:27 UTC, elocremarc commented on collection.json
> +  {"inscriptionId": "597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0"},
Only submit 1 inscriptionId

2023-07-26 06:28 UTC, 759894780 commented on collection.json
> +  {"inscriptionId": "597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0"},
597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0 i only have this one

2023-07-26 06:43 UTC, 759894780 reviewed
{ “inscriptionId”：“ 597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0 ” }
i only have this one
boss

2023-07-26 06:43 UTC, 759894780 commented on collection.json
>    {"inscriptionId": "21baeba288bd984d61e9ed2298172ea3706547bba601d2ce36cdfd7ccb761f02i0"}
{ “inscriptionId”：“ 597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0 ” }

2023-07-26 07:31 UTC, elocremarc commented on collection.json
> +  {"inscriptionID": "597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0"}
@759894780 you put in twice

2023-07-26 07:53 UTC, 759894780 commented on collection.json
> +  {"inscriptionID": "597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0"}
can you help me delete one i dont know how

2023-07-26 08:01 UTC, 759894780 commented on collection.json
> +  {"inscriptionID": "597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0"}
Maybe I removed 152
@elocremarc

2023-07-29 17:39 UTC, 759894780 commented on collection.json
> +  {"inscriptionID": "597e7a0d6b089bfcbc5aecc540b99d8b6ab0c7add8064804749970f5835a307bi0"}
help me

2026-02-12 18:49 UTC, Nuropunk commented
Closing as part of Feb 12, 2026 GitHub backlog cleanup. Reopen or recreate if this is still needed.

2026-02-12 18:49 UTC, closed without merging