Add new inscription ID
cypherpunklab/manifesto pull request #263
Opened 2023-07-26 06:47 UTC by wwwyyy6

2023-07-26 07:40 UTC, elocremarc approved these changes

2023-07-29 09:11 UTC, elocremarc requested changes

2023-07-29 09:11 UTC, elocremarc commented on collection.json
> +  {"inscriptionId": "21baeba288bd984d61e9ed2298172ea3706547bba601d2ce36cdfd7ccb761f02i0"},
Why are you adding this again?

2026-02-12 18:49 UTC, Nuropunk commented
Closing as part of Feb 12, 2026 GitHub backlog cleanup. Reopen or recreate if this is still needed.

2026-02-12 18:49 UTC, closed without merging