Add new inscription ID
cypherpunklab/manifesto pull request #266
Opened 2023-07-26 06:49 UTC by jkman1993

2023-07-29 09:16 UTC, elocremarc commented on collection.json
>    {"inscriptionId": "78702c77b14226c936dd7384cfb284905808402619b2bb7a78cc2a4e16a6a448i0"},
Only submit 1

2023-07-29 09:16 UTC, elocremarc commented on collection.json
> -]
Don't delete this.

2023-07-29 09:17 UTC, elocremarc requested changes
See comments

2026-02-12 18:49 UTC, Nuropunk commented
Closing as part of Feb 12, 2026 GitHub backlog cleanup. Reopen or recreate if this is still needed.

2026-02-12 18:49 UTC, closed without merging