New manifesto
cypherpunklab/manifesto pull request #53
Opened 2023-07-02 13:33 UTC by pu936

2023-07-02 21:31 UTC, elocremarc requested changes

2023-07-02 21:31 UTC, elocremarc commented on collection.json
> -]
Dont delete this. We need to have it at the end

2023-07-03 14:26 UTC, pu936 commented on collection.json
> -]
Am I good now..? haha sorry real noob with it - first time using and trying to figure out some stuff lol

2023-07-05 01:05 UTC, elocremarc approved these changes

2023-07-05 01:05 UTC, merged