Add new inscription ID
cypherpunklab/manifesto pull request #59
Opened 2023-07-02 22:22 UTC by Acika1991

2023-07-03 01:20 UTC, elocremarc requested changes

2023-07-03 01:20 UTC, elocremarc commented on collection.json
> -]
Don't delete the ]
put your entry after line 15 and add a comma to line 15

Should look like this
```
{"inscriptionId": "22c619a3f9d0d7682e6c9f8e7113659f50ecf447e42d74a291f0850965a59f5bi0"},
{"inscriptionId": "f53714c0ec3beecb6e4bfb52a95178af8d006e3f1a08ce6058bbcbf18c721b87i0"}
]
```
Your commit should look like this
```diff
-{"inscriptionId": "22c619a3f9d0d7682e6c9f8e7113659f50ecf447e42d74a291f0850965a59f5bi0"}
+{"inscriptionId": "22c619a3f9d0d7682e6c9f8e7113659f50ecf447e42d74a291f0850965a59f5bi0"},
+{"inscriptionId": "f53714c0ec3beecb6e4bfb52a95178af8d006e3f1a08ce6058bbcbf18c721b87i0"}
]
```

2023-07-03 13:13 UTC, Acika1991 commented on collection.json
> -]
gm eloc ty .. do I need to commit after making change ?

  {"inscriptionId": "22c619a3f9d0d7682e6c9f8e7113659f50ecf447e42d74a291f0850965a59f5bi0"},
  {"inscriptionId": "f53714c0ec3beecb6e4bfb52a95178af8d006e3f1a08ce6058bbcbf18c721b87i0"}
  ]

2023-07-03 13:37 UTC, Acika1991 commented on collection.json
> -]
![Changes](https://github.com/cypherpunklab/manifesto/assets/138405715/d0d7ba2c-1016-4f94-86b3-f0bf76bd6acd)

2023-07-05 01:58 UTC, elocremarc approved these changes

2023-07-05 01:58 UTC, merged